apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
