apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-gateway
spec:
  type: {{ .Values.service.type }}
  selector:
    app: gateway
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000