apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}-gateway
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: "{{ .Values.image.gateway.repository }}:{{ .Values.image.gateway.tag }}"
          ports:
            - containerPort: 3000
          env:
            - name: JWT_SECRET
              value: "{{ .Values.env.JWT_SECRET }}"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20