apiVersion: v1
kind: Service
metadata:
  name: {{ include "inventaris.fullname" . }}-gateway
  labels:
    app: gateway
spec:
  type: {{ .Values.services.gateway.type }}
  ports:
    - port: {{ .Values.services.gateway.port }}
      targetPort: {{ .Values.services.gateway.targetPort }}
      protocol: TCP
  selector:
    app: gateway