{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fullname" . }}-ingress
  labels:
    app: inventory-system
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "fullname" . }}-frontend
                port:
                  number: 80
          - path: /api/gateway
            pathType: Prefix
            backend:
              service:
                name: {{ include "fullname" . }}-gateway
                port:
                  number: 80
{{- end }}
