apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-inventory
  labels:
    app: inventory-service
spec:
  selector:
    app: inventory-service
  ports:
    - name: http
      port: 80
      targetPort: 3002
  type: ClusterIP
