apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: "{{ .Values.image.repository }}/inventory-service:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3002
          env:
            - name: DB_URI
              value: "postgres://{{ .Values.env.DB_USER }}:{{ .Values.env.DB_PASSWORD }}@{{ .Values.env.DB_HOST }}:5432/inventorydb"
            - name: RABBITMQ_URL
              value: "{{ .Values.env.RABBITMQ_URL }}"
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 10