apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $svc.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  to:
    kind: Service
    name: {{ $svc.name }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge