apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-gateway
spec:
  type: {{ .Values.service.type }}
  selector:
    app: gateway
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
