apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-transaction
  labels:
    app: transaction-service
spec:
  selector:
    app: transaction-service
  ports:
    - name: http
      port: 80
      targetPort: 3003
  type: ClusterIP
