apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}-user
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: "{{ .Values.image.userService.repository }}:{{ .Values.image.userService.tag }}"
          ports:
            - containerPort: 3001
          env:
            - name: DB_URI
              value: "postgres://{{ .Values.env.DB_USER }}:{{ .Values.env.DB_PASSWORD }}@{{ .Values.env.DB_HOST }}:5432/userdb"
            - name: JWT_SECRET
              value: "{{ .Values.env.JWT_SECRET }}"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 20